/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   Do not edit this file directly. Any changes will be lost.           ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import type Opa5 from "sap/ui/test/Opa5";
import type { actions as ListReportActions, assertions as ListReportAssertions } from "sap/fe/test/ListReport";
import type { actions as ObjectPageActions, assertions as ObjectPageAssertions } from "sap/fe/test/ObjectPage";
import type { actions as TemplatePageActions, assertions as TemplatePageAssertions } from "sap/fe/test/TemplatePage";
import type Shell from "sap/fe/test/Shell";
import type BaseArrangements from "sap/fe/test/BaseArrangements";
import type { actions as ProductsListGeneratedCustomActions, assertions as ProductsListGeneratedCustomAssertions } from "../pages/ProductsList.gen";
import type { actions as ProductsObjectPageGeneratedCustomActions, assertions as ProductsObjectPageGeneratedCustomAssertions } from "../pages/ProductsObjectPage.gen";

export type Given = Opa5 & BaseArrangements & {
    iTearDownMyApp: () => Given;
    iStartMyApp: (sAppHash?: string, mInUrlParameters?: object) => Given;
    and: Given;
};

export type When = Opa5 & BaseArrangements & {
    onTheProductsListGenerated: Opa5 & ListReportActions & TemplatePageActions & typeof ProductsListGeneratedCustomActions;
    onTheProductsObjectPageGenerated: Opa5 & ObjectPageActions & TemplatePageActions & typeof ProductsObjectPageGeneratedCustomActions;
    onTheShell: Shell;
};

export type Then = Opa5 & BaseArrangements & {
    onTheProductsListGenerated: Opa5 & ListReportAssertions & TemplatePageAssertions & typeof ProductsListGeneratedCustomAssertions;
    onTheProductsObjectPageGenerated: Opa5 & ObjectPageAssertions & TemplatePageAssertions & typeof ProductsObjectPageGeneratedCustomAssertions;
    onTheShell: Shell;
};
